import { test, expect } from '@playwright/test';
// could be sth else depending on id's generated by DB but there's no better way atm

test('updateUser', async ({ page }) => {
  await page.goto('http://localhost/usermanagement/');
  await page.getByRole('button', { name: 'Aktualisieren' }).click();
  await page.getByRole('button', { name: 'bearbeiten' }).nth(0).click();
  await page.getByPlaceholder('Vorname').click();
  await page.getByPlaceholder('Vorname').fill('Tester');
  await page.getByPlaceholder('Vorname').press('Tab');
  await page.getByPlaceholder('Nachname').fill('Schwabe');
  await page.getByPlaceholder('Nachname').press('Tab');
  await page.getByPlaceholder('Email').fill('schwabe.daniel@yahoo.de');
  await page.getByPlaceholder('Email').press('Tab');
  await page.getByPlaceholder('Passwort').fill('Test123!');
  await page.getByRole('button', { name: 'Abschicken' }).click();
  await expect(page.locator('#answerMessage')).toHaveText('Erfolgreich bearbeitet.');
});

test('updateUserExistingEmail', async ({ page }) => {
  await page.goto('http://localhost/usermanagement/');
  await page.getByRole('button', { name: 'Aktualisieren' }).click();
  await page.getByRole('button', { name: 'bearbeiten' }).nth(0).click();
  await page.getByPlaceholder('Vorname').click();
  await page.getByPlaceholder('Vorname').fill('Tester');
  await page.getByPlaceholder('Vorname').press('Tab');
  await page.getByPlaceholder('Nachname').fill('Schwabe');
  await page.getByPlaceholder('Nachname').press('Tab');
  await page.getByPlaceholder('Email').fill('schwabe.daniel@yahoo.de');
  await page.getByPlaceholder('Email').press('Tab');
  await page.getByPlaceholder('Passwort').fill('Test123!');
  await page.getByRole('button', { name: 'Abschicken' }).click();
  await expect(page.locator('#answerMessage')).toHaveText('Zu dieser E-Mail existiert bereits ein Account.');
});